// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNhaTro.Data;

#nullable disable

namespace QLNhaTro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("QLNhaTro.Models.CaiDat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaDien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("GiaNuoc")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhiDichVu")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNhaTro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CaiDats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiaDien = 3500m,
                            GiaNuoc = 15000m,
                            NgayCapNhat = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhiDichVu = 100000m,
                            TenNhaTro = "Nhà Trọ",
                            ThemeMode = "light"
                        });
                });

            modelBuilder.Entity("QLNhaTro.Models.ChiSoDienNuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChiSoDienCu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChiSoDienMoi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChiSoNuocCu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChiSoNuocMoi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thang")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhongId", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("ChiSoDienNuocs");
                });

            modelBuilder.Entity("QLNhaTro.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HopDongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhiDichVu")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Thang")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HopDongId");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QLNhaTro.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaThueThucTe")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("KhachThueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhongId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KhachThueId");

                    b.HasIndex("MaHopDong")
                        .IsUnique();

                    b.HasIndex("PhongId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("QLNhaTro.Models.KhachThue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.ToTable("KhachThues");
                });

            modelBuilder.Entity("QLNhaTro.Models.Phong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DienTich")
                        .HasColumnType("REAL");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong")
                        .IsUnique();

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QLNhaTro.Models.ThanhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("HopDongId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuanHe")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HopDongId");

                    b.ToTable("ThanhViens");
                });

            modelBuilder.Entity("QLNhaTro.Models.ChiSoDienNuoc", b =>
                {
                    b.HasOne("QLNhaTro.Models.Phong", "Phong")
                        .WithMany("ChiSoDienNuocs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QLNhaTro.Models.HoaDon", b =>
                {
                    b.HasOne("QLNhaTro.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QLNhaTro.Models.HopDong", b =>
                {
                    b.HasOne("QLNhaTro.Models.KhachThue", "KhachThue")
                        .WithMany("HopDongs")
                        .HasForeignKey("KhachThueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNhaTro.Models.Phong", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QLNhaTro.Models.ThanhVien", b =>
                {
                    b.HasOne("QLNhaTro.Models.HopDong", "HopDong")
                        .WithMany("ThanhViens")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QLNhaTro.Models.HopDong", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("ThanhViens");
                });

            modelBuilder.Entity("QLNhaTro.Models.KhachThue", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QLNhaTro.Models.Phong", b =>
                {
                    b.Navigation("ChiSoDienNuocs");

                    b.Navigation("HopDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
